xwayland disable
seat seat0 fallback true
output * mode 1200x800
default_border none
for_window [title="zgui transparency"] floating enable, border none, resize set width 320 px height 240 px, move position 160 px 140 px
