[package]
name = "zgui-desktop"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
zgui = { path = "../zgui" }
zgui-gpu = { path = "../zgui-gpu" }
winit = "0.30.13"
softbuffer = "0.4.8"
fontdue = "0.9.3"
cosmic-text = "0.14.2"
arboard = { version = "3.6.1", default-features = false }
accesskit = "0.24.1"
unicode-segmentation = "1.12"
accesskit_winit = "0.33.2"
rfd = "=0.17.2"
open = "=5.4.4"
zgui-workload = { path = "../../comparisons/workload" }

[target.'cfg(target_os = "linux")'.dependencies]
smithay-clipboard = "0.7.3"
dbus = "=0.9.12"
dbus-crossroads = "=0.5.3"
wayland-client = "=0.31.15"
wayland-backend = { version = "=0.3.17", features = ["client_system"] }
wayland-protocols = { version = "=0.32.13", features = ["client", "unstable"] }

[target.'cfg(target_os = "macos")'.dependencies]
muda = { version = "=0.18.0", default-features = false }
objc2 = "=0.6.4"
objc2-app-kit = { version = "=0.3.2", default-features = false, features = ["std", "NSApplication", "NSResponder"] }
objc2-foundation = { version = "=0.3.2", default-features = false, features = ["std", "NSArray", "NSObject", "NSString", "NSURL"] }

[[bin]]
name = "zgui-demo"
path = "src/main.rs"

[dev-dependencies]
accesskit_consumer = "0.38.0"
