[package]
name = "zgui"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
unicode-segmentation = "1.12"
taffy = { version = "=0.9.0", default-features = false, features = ["std", "taffy_tree", "flexbox", "grid", "content_size"] }

[target.'cfg(target_os = "macos")'.dependencies]
objc2-core-foundation = "0.3.2"
objc2-core-video = "0.3.2"
